
package prova.project2.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.9
 * Tue Jun 27 14:16:18 BRT 2017
 * Generated source version: 3.1.9
 */

@XmlRootElement(name = "getPossibleCampanhas", namespace = "http://service.project2.prova/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getPossibleCampanhas", namespace = "http://service.project2.prova/")

public class GetPossibleCampanhas {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

